# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=200)),
                ('app_name', models.CharField(max_length=200)),
                ('dev_name', models.CharField(max_length=200)),
                ('query_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchapp.Query')),
            ],
        ),
    ]
