# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('Query', 'Queries')
    ]
